name: contact_picker_example
description: Demonstrates how to use the contact_picker plugin.
environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  contact_picker:
    path: ../

flutter:
  uses-material-design: true
  